# -------------------*** ***Numpy*** **------------------

- NumPy (Numerical Python) is a fundamental Python library for scientific and numerical computing. It provides powerful support for multi-dimensional arrays and matrices, along with a wide range of mathematical functions to efficiently operate on them.

- Array minority me impotance deta hai . array = [1,2,4,5,'a',4] present of single 'a' now type of array is string.

- numpy has some extra data types and refer to data types with one character like i for integer.

- i - integer
- b - boolean
- u - unsigend integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - boject
- S - string
- U - unicode string
- v - fixed chunk of memory for other type (void)

In [1]:
import numpy as np # har bar numpy na likhana pade isliye as np.
np.__version__

'1.26.4'

In [10]:
lst = [1,2,3,4,5,5,6,7]    # in list or  tuple... we can store only 1 dimentional array. so we use numpy
print(lst)
print(type(lst))

[1, 2, 3, 4, 5, 5, 6, 7]
<class 'list'>


In [ ]:
lst = [1,2,3,4,'5',5,6,7]    
print(lst)
print(type(lst))

[1, 2, 3, 4, '5', 5, 6, 7]
<class 'list'>


In [15]:
arr = np.array([1,2,3,4,'5',5,6,7])
print(arr.dtype)

<U11


# Zero Dimension array -

In [ ]:
zero_dim = np.array(10)

print(zero_dim)

print(type(zero_dim))
print(f'Dimention of array {zero_dim.ndim}')

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [16]:
print('1 dimentinol Array')
a = np.array([1,2,3,4,5])
print(a,'\n\n')

print('2 dimentinol Array')
b = np.array([[2,3],[5,6],[3,7]])    # row column must be same number of elements.
print(b,'\n\n')


print('3 dimentinol Array')
c = np.array([[[1,2],[3,98]],
                    [[5,6],[7,8]] , [[5,5],[6,6]]])
print(c,'\n\n')

print(c[1,1,1]) # how to access 3d values .
print(type(c))

1 dimentinol Array
[1 2 3 4 5] 


2 dimentinol Array
[[2 3]
 [5 6]
 [3 7]] 


3 dimentinol Array
[[[ 1  2]
  [ 3 98]]

 [[ 5  6]
  [ 7  8]]

 [[ 5  5]
  [ 6  6]]] 


8
<class 'numpy.ndarray'>


In [ ]:
arr = np.array([1,2,3,4,5,5,6,76,7,8,9,9,9],ndmin=10)
print(arr)
print(arr.ndim)


[[[[[[[[[[ 1  2  3  4  5  5  6 76  7  8  9  9  9]]]]]]]]]]
10


# Find max and minmum value in array .

In [22]:
arr = np.array([8,8,2,3,4,5,5,6,76,7,8,9,9,9])
print(arr.argmax())       # return hightest index value.
print(arr.argmin())

8
2


# **Slicing** -

In [ ]:
ary = np.array([1,2,3,4,5,5,6,76,7,8,9,9,9]) # 1D
print(ary[::2])


[1 3 5 6 7 9 9]


In [ ]:
ary = np.array([[1,2,3,4,5],[22,33,45,67,88]])   # 2D

print(ary[1,1:4])
print(ary[1,1:])
print(ary[1,:4])

print(ary[1][2])  # We aolso use this method.

[33 45 67]
[33 45 67 88]
[22 33 45 67]
45


In [4]:
ary = np.array([[[1,2,3,],[45,67,88],[55,66,77]]]) #3D

print(ary[0,1,0:2])


print(ary[0][2][2])

[45 67]
77


In [48]:
print(a.size)  # IT print how many element in the array.
print(b.size)
print(c.size,'\n\n')


print(c.dtype)
g = np.array([2.3,4.56,6,7.9,])

print(g.dtype)  # return data type of array


5
4
12 


int64
float64


In [49]:
print(a.shape)  # it contain 5 columns.
print(b.shape)  # It contain 2 Rows 2 Column.
print(c.shape)  # 3 Array of 2 rows 2 column.

(5,)
(2, 2)
(3, 2, 2)


In [6]:
j = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15]])

print(j.shape)
print(j.transpose()) # It convert Row into column. but it doese'nt change actual dimentional.
print(j.transpose().shape,'\n')
print(j.shape)

(3, 5)
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(5, 3) 

(3, 5)


In [51]:
np.empty((4,4),dtype=int)
#np.empty((4,4),dtype=float)

array([[   588223257,            0, 489626271861, 433791696995],
       [498216206368, 468151435365, 476741369968, 416611827826],
       [450971566194, 519691042924, 502511173664, 416611827822],
       [416611827830, 463856468073, 420906795105, 433791697004]])

In [52]:
#x = np.ones(10)    # iska default data type rahta hai jo float hai .

x = np.ones((2,5),dtype=int)

# x = np.ones((4,5), dtype = int)


x
#print(x)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
x = np.zeros(4)             # ye 0 kee liyee .

# x = np.zeros(3,5)

# x = np.zeros((4,5), dtype = int)
# x = np.zeros((2,5), dtype = str)
#x = np.zeros((4,5), dtype = bool)

x
#print(x)

array([0., 0., 0., 0.])

# arange() function - 
            - array range
            - Another method is linspace and longspace.

In [1]:
import numpy as np
a = np.arange(1,20)   # np.arange(start,end,step)
a = np.arange(2,20,2)
a = np.arange(3,30,3)

print(a)

[ 3  6  9 12 15 18 21 24 27]


In [3]:
arr = np.arange(2,10)
print(arr)
print(arr.ndim)

[2 3 4 5 6 7 8 9]
1


In [ ]:
reshape_2D = np.reshape(arr,(4,2))   # Do element matlab 2D array .
print(reshape_2D)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


# reshap() - 
            - To change dimentional.

In [55]:
a = a.reshape((3,3))   # arr.reshape((row,columns)) =[ 3  6  9 12 15 18 21 24 27]
a

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [56]:
a = a.ravel()
a

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [57]:
b = np.arange(1,100,2)
b

b = b.reshape(10,5)
b

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [58]:
b = b.flatten()  # reverse process of reshapeing.
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## 1. a.ravel - Written only different view of original array. 2. if you modify the array you would notice that the value of original array also change 3. ravel() is faster than flatten() as it does not occupy any memory 4. reveal is a library level function.

## 2. a.flatten() - 1. return copy of the array 2. if you modify any value of this array value of original array is not affected 3. flatten is comparatively slower than Revel as it occupies memory wood flatten is a method of an ndarray object.

# ------------------------- Slicing operation -----------------------------

In [7]:
a = np.arange(1,51)
a = a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [8]:
print(a[0])

print(a[0,0])

print(a[2,1])

print(a[3,4])

[1 2 3 4 5]
1
12
20


In [ ]:
print(a,'\n')

print(a[0:3],'\n')   # a[rows:kaha tk]

print(a[:,2],'\n')  # print column.

print(a[2:5,4],'\n')    # 2nd row se shuru karega 4th tk  5th column me .

print(a[:,2:5],'\n')  #.dtype     2nd colunm se shuru karenga and 5 tk print karega .

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[ 3  8 13 18 23 28 33 38 43 48] 

[15 20 25] 

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]
 [18 19 20]
 [23 24 25]
 [28 29 30]
 [33 34 35]
 [38 39 40]
 [43 44 45]
 [48 49 50]] 



#

# Mathametical oparation methods . 

In [8]:
a = np.arange(0,18).reshape((6,3))
b = np.arange(20,38).reshape((6,3))

print(a,'\n\n')
print(b,'\n\n------After adding \n \n')

a+b

# np.add(a,b)  also we use ..

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]] 


[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]] 

------After adding 
 



array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [63]:
a-b  # np.subtraact(a,b)  a*b np.multiply(a,b)  a/b.....

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [64]:
# a@b perform karne ke liyee [6,3]
#                            [3,6]  hona chahiyee.

b = b.reshape(3,6)


print(a.shape)
print(b.shape)
b

(6, 3)
(3, 6)


array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37]])

In [65]:
a@b # for matrix multiplication . a.dot(b)

array([[  90,   93,   96,   99,  102,  105],
       [ 324,  336,  348,  360,  372,  384],
       [ 558,  579,  600,  621,  642,  663],
       [ 792,  822,  852,  882,  912,  942],
       [1026, 1065, 1104, 1143, 1182, 1221],
       [1260, 1308, 1356, 1404, 1452, 1500]])

In [66]:
print(b.max())
print(b.min())
print(b.argmax())   # sabse badi value kaha per hai yah batata hai.

print(a.argmax())

37
20
17
17


In [67]:
np.sum(b)

np.int64(513)

In [68]:
np.sqrt(b)  # np.log(b)

array([[4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558,
        5.56776436],
       [5.65685425, 5.74456265, 5.83095189, 5.91607978, 6.        ,
        6.08276253]])

In [69]:
np.sum(b, axis = 1)  # sum of row one by one .

array([135, 171, 207])

In [70]:
o = np.arange(334)
print(o)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [6]:
fri_arr = np.array([3,6,7,6,8,8])
print(fri_arr)
sec_arr = np.array([1,2,3,4,5,6])

add = fri_arr+sec_arr
print(add)

[3 6 7 6 8 8]
[ 4  8 10 10 13 14]


In [ ]:
Add = np.add(fri_arr,sec_arr)  # np.substract , np.mul
print(Add)

[ 4  8 10 10 13 14]


# Matrix multiplication

In [2]:
import numpy as np
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[5,6],[7,8]])

matrix_mul = np.matmul(arr_1,arr_2)
print(matrix_mul)

[[19 22]
 [43 50]]


# Sorting

In [14]:
first_arr = np.array([3,6,7,6,8,8,])
print(first_arr,'\n')

sort_first_arr = np.sort(first_arr)
print(sort_first_arr)


[3 6 7 6 8 8] 

[3 6 6 7 8 8]


In [ ]:
two_arr = np.array([[3,523,65],[46,463,6]])
print(two_arr)
print("_"*50)
sort_two_arr = np.sort(two_arr)
print(sort_two_arr)
print("_"*50)

sort_two_arr = np.sort(two_arr,axis=0)
print(sort_two_arr)
print("_"*50)

sort_two_arr = np.sort(two_arr,axis=1)
print(sort_two_arr)

[[  3 523  65]
 [ 46 463   6]]
__________________________________________________
[[  3  65 523]
 [  6  46 463]]
__________________________________________________
[[  3 463   6]
 [ 46 523  65]]
__________________________________________________
[[  3  65 523]
 [  6  46 463]]


axis=0 → इसका मतलब है rows के ऊपर काम करना, यानी column-wise operation.

जब तुम np.sort(..., axis=0) लिखते हो, तो NumPy हर column को अलग-अलग sort करता है।

Rows की positions बदलती हैं ताकि हर column sorted हो जाए।

axis=1 → इसका मतलब है columns के ऊपर काम करना, यानी row-wise operation.

जब तुम np.sort(..., axis=1) लिखते हो, तो NumPy हर row को अलग-अलग sort करता है।

Columns की positions बदलती हैं ताकि हर row sorted हो जाए।