In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.6'

In [4]:
l1 = [4,3,56,7,86,]
print(l1)
print(type(l1))

[4, 3, 56, 7, 86]
<class 'list'>


In [6]:
arr = np.array(l1)
print(arr)
print(type(arr))

[ 4  3 56  7 86]
<class 'numpy.ndarray'>


# Zero Dimensional Array

In [10]:
zero_arr = np.array(10)
print(zero_arr)
print(type(zero_arr))
print(f"Dimension of an array {zero_arr.ndim}")

10
<class 'numpy.ndarray'>
Dimension of an array 0


# One Dimension Array

In [11]:
one_d_arr = np.array([10])
print(one_d_arr)
print(type(one_d_arr))
print(f"Dimension of an array {one_d_arr.ndim}")

[10]
<class 'numpy.ndarray'>
Dimension of an array 1


In [12]:
one_d_arr = np.array([10,6,3,6,7,])
print(one_d_arr)
print(type(one_d_arr))
print(f"Dimension of an array {one_d_arr.ndim}")

[10  6  3  6  7]
<class 'numpy.ndarray'>
Dimension of an array 1


In [15]:
two_d_arr = np.array([[10,6],[5,7]])
print(two_d_arr)
print(type(two_d_arr))
print(f"Dimension of an array {two_d_arr.ndim}")
print(f"Shape of an array {two_d_arr.shape}")
print(f"Data Type of an array {two_d_arr.dtype}")

[[10  6]
 [ 5  7]]
<class 'numpy.ndarray'>
Dimension of an array 2
Shape of an array (2, 2)
Data Type of an array int64


In [17]:
two_d_arr = np.array([[10.56,6],[5,7]])
print(two_d_arr)
print(type(two_d_arr))
print(f"Dimension of an array {two_d_arr.ndim}")
print(f"Shape of an array {two_d_arr.shape}")
print(f"Data Type of an array '{two_d_arr.dtype}'")

[[10.56  6.  ]
 [ 5.    7.  ]]
<class 'numpy.ndarray'>
Dimension of an array 2
Shape of an array (2, 2)
Data Type of an array 'float64'


In [1]:
import numpy as np
arr = np.array([['1',2],['8',5]])

print(arr.ndim)
print(arr.dtype)
print(arr.shape)

2
<U11
(2, 2)


In [19]:
two_d_arr = np.array([[10.56,6],[5,78]])
print(two_d_arr)
print(type(two_d_arr))
print(f"Dimension of an array {two_d_arr.ndim}")
print(f"Shape of an array {two_d_arr.shape}")
print(f"Data Type of an array '{two_d_arr.dtype}'")

[[10.56  6.  ]
 [ 5.   78.  ]]
<class 'numpy.ndarray'>
Dimension of an array 2
Shape of an array (2, 2)
Data Type of an array 'float64'


In [21]:
two_d_arr = np.array([[10.56,6,6],[5,7,8]])
print(two_d_arr)
print(type(two_d_arr))
print(f"Dimension of an array {two_d_arr.ndim}")
print(f"Shape of an array {two_d_arr.shape}")
print(f"Data Type of an array '{two_d_arr.dtype}'")

[[10.56  6.    6.  ]
 [ 5.    7.    8.  ]]
<class 'numpy.ndarray'>
Dimension of an array 2
Shape of an array (2, 3)
Data Type of an array 'float64'


In [23]:
two_d_arr = np.array([[10.56,6,6],
                      [5,7,8],
                      [55,66,77]])
print(two_d_arr)
print(type(two_d_arr))
print(f"Dimension of an array {two_d_arr.ndim}")
print(f"Shape of an array {two_d_arr.shape}")
print(f"Data Type of an array '{two_d_arr.dtype}'")
print(f"Size of an array '{two_d_arr.size}'")

[[10.56  6.    6.  ]
 [ 5.    7.    8.  ]
 [55.   66.   77.  ]]
<class 'numpy.ndarray'>
Dimension of an array 2
Shape of an array (3, 3)
Data Type of an array 'float64'
Size of an array '9'


In [26]:
three_d_arr = np.array([[[10,6,6],
                      [55,66,77]]])
print(three_d_arr)
print(type(three_d_arr))
print(f"Dimension of an array {three_d_arr.ndim}")
print(f"Shape of an array {three_d_arr.shape}")
print(f"Data Type of an array '{three_d_arr.dtype}'")
print(f"Size of an array '{three_d_arr.size}'")

[[[10  6  6]
  [55 66 77]]]
<class 'numpy.ndarray'>
Dimension of an array 3
Shape of an array (1, 2, 3)
Data Type of an array 'int64'
Size of an array '6'


In [28]:
three_d_arr = np.array([[[10,6,6],[55,66,77]],
                      [[2,3,4],[6,7,8]]])
print(three_d_arr)
print(type(three_d_arr))
print(f"Dimension of an array {three_d_arr.ndim}")
print(f"Shape of an array {three_d_arr.shape}")
print(f"Data Type of an array '{three_d_arr.dtype}'")
print(f"Size of an array '{three_d_arr.size}'")

[[[10  6  6]
  [55 66 77]]

 [[ 2  3  4]
  [ 6  7  8]]]
<class 'numpy.ndarray'>
Dimension of an array 3
Shape of an array (2, 2, 3)
Data Type of an array 'int64'
Size of an array '12'


In [33]:
three_d_arr = np.array([[[10,6,6],[55,66,77]],
                      [[2,3,4],[6,7,8]]],ndmin = 64)
print(three_d_arr)
print(type(three_d_arr))
print(f"Dimension of an array {three_d_arr.ndim}")
print(f"Shape of an array {three_d_arr.shape}")
print(f"Data Type of an array '{three_d_arr.dtype}'")
print(f"Size of an array '{three_d_arr.size}'")

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[10
                                                                 6
                                                                 6]
                                                               [55
                                                                66
                                                                77]]

                                                              [[ 2
                                                                 3
                                                                 4]
                                                               [ 6
                                                                 7
                                                                 8]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
<class 'numpy.ndarray'>
Dimension of an array 64
Shape of an array (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [2]:
zer_arr = np.zeros(shape=(3,2))
print(zer_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [1]:
import numpy as np
zer_arr = np.zeros(shape=(3,3), dtype=int)
print(zer_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
